[linters]
enable = [
	"asciicheck",
	"asasalint",
	"bidichk",
	"bodyclose",
	"containedctx",
	"contextcheck",
	"decorder",
	"dogsled",
	"dupl",
	"dupword",
	"durationcheck",
	"errcheck",
	"errchkjson",
	"errname",
	"errorlint",
	"execinquery",
	"exhaustive",
	"exhaustruct",
	"exportloopref",
	"forcetypeassert",
	"gci",
	"ginkgolinter",
	"gocheckcompilerdirectives",
	"gochecksumtype",
	"goconst",
	"gocritic",
	"godot",
	"gofmt",
	"gofumpt",
	"goimports",
	"goprintffuncname",
	"gosec",
	"gosimple",
	"gosmopolitan",
	"govet",
	"grouper",
	"importas",
	"inamedparam",
	"ineffassign",
	"interfacebloat",
	"ireturn",
	"loggercheck",
	"makezero",
	"mirror",
	"misspell",
	"musttag",
	"nilerr",
	"nilnil",
	"nlreturn",
	"noctx",
	"nolintlint",
	"nonamedreturns",
	"nosprintfhostport",
	"paralleltest",
	"perfsprint",
	"prealloc",
	"predeclared",
	"promlinter",
	"protogetter",
	"reassign",
	"revive",
	"rowserrcheck",
	"sloglint",
	"sqlclosecheck",
	"staticcheck",
	"stylecheck",
	"tagalign",
	"tagliatelle",
	"tenv",
	"testableexamples",
	"testifylint",
	"thelper",
	"tparallel",
	"unconvert",
	"unparam",
	"unused",
	"usestdlibvars",
	"wastedassign",
	"whitespace",
	"wsl",
	"zerologlint",
]
